(defun f (lst)
  (cond ((every #'(lambda (elem)
                     (cond ((> elem 0) T)
                           (T nil)))
                (first lst))
         (mapcar #'(lambda (sub_lst)
                     (mapcar #'(lambda (elem)
                                 (* elem 2))
                             sub_lst))
                 lst))
        ((every #'(lambda (elem)
                     (cond ((< elem 0) T)
                           (T nil)))
                (first lst))
         (mapcar #'(lambda (sub_lst)
                     (* (first sub_lst) (second sub_lst)))
                 lst))
        (t (apply #'+ (mapcan #'(lambda (sub_lst)
                                  (remove-if-not #'numberp sub_lst))
                              lst)))))

(print (f '((-1 2) (3 4) (5 6))))


